-- Services --
USE ROLE SYSADMIN;
DROP SERVICE WEAVIATE_PRODUCT_REVIEWS.PUBLIC.OLLAMA;

-- Compute Pools --
USE ROLE SYSADMIN;
DROP COMPUTE POOL OLLAMA_POOL;

-- Weaviate Database --
USE ROLE SYSADMIN;
DROP DATABASE WEAVIATE_PRODUCT_REVIEWS;

-- Weaviate Warehouse --
USE ROLE SYSADMIN;
DROP WAREHOUSE WEAVIATE_WAREHOUSE;

-- Weaviate User --
USE ROLE USERADMIN;
DROP USER weaviate_user;

-- Weaviate Role --
USE ROLE SECURITYADMIN;
DROP ROLE WEAVIATE_ROLE;

-- OAuth Integration --
USE ROLE ACCOUNTADMIN;
DROP SECURITY INTEGRATION SNOWSERVICES_INGRESS_OAUTH;