-- OAuth Integration --
USE ROLE ACCOUNTADMIN;
CREATE SECURITY INTEGRATION SNOWSERVICES_INGRESS_OAUTH
  TYPE=oauth
  OAUTH_CLIENT=snowservices_ingress
  ENABLED=true;

-- Bind Service Grant
USE ROLE ACCOUNTADMIN;
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE SYSADMIN;

-- Weaviate Role --
USE ROLE SECURITYADMIN;
CREATE ROLE WEAVIATE_ROLE;

-- Weaviate User --
USE ROLE USERADMIN;
CREATE USER weaviate_user
  PASSWORD='weaviate123'
  DEFAULT_ROLE = WEAVIATE_ROLE
  DEFAULT_SECONDARY_ROLES = ('ALL')
  MUST_CHANGE_PASSWORD = FALSE;

-- Grant Role to User --
USE ROLE SECURITYADMIN;
GRANT ROLE WEAVIATE_ROLE TO USER weaviate_user;

-- Weaviate Warehouse --
USE ROLE SYSADMIN;
CREATE OR REPLACE WAREHOUSE WEAVIATE_WAREHOUSE WITH
  WAREHOUSE_SIZE='X-SMALL'
  AUTO_SUSPEND = 180
  AUTO_RESUME = true
  INITIALLY_SUSPENDED=true;

-- Weaviate Database --
-- + image repo --
-- + stages --
USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS WEAVIATE_PRODUCT_REVIEWS;
USE DATABASE WEAVIATE_PRODUCT_REVIEWS;
CREATE IMAGE REPOSITORY WEAVIATE_PRODUCT_REVIEWS.PUBLIC.WEAVIATE_REPO;
CREATE OR REPLACE STAGE YAML_STAGE;
CREATE OR REPLACE STAGE DATA ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');
CREATE OR REPLACE STAGE FILES ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- Grants for Weaviate Role --
USE ROLE SECURITYADMIN;
GRANT ALL PRIVILEGES ON DATABASE WEAVIATE_PRODUCT_REVIEWS TO WEAVIATE_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA WEAVIATE_PRODUCT_REVIEWS.PUBLIC TO WEAVIATE_ROLE;
GRANT ALL PRIVILEGES ON WAREHOUSE WEAVIATE_WAREHOUSE TO WEAVIATE_ROLE;
GRANT ALL PRIVILEGES ON STAGE WEAVIATE_PRODUCT_REVIEWS.PUBLIC.FILES TO WEAVIATE_ROLE;

-- Compute Pools --
USE ROLE SYSADMIN;
CREATE COMPUTE POOL OLLAMA_POOL
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = GPU_NV_M;

DESCRIBE COMPUTE POOL OLLAMA_POOL;

-- Put specs in stage --
PUT file:///path/to/ollama.yaml @yaml_stage overwrite=true auto_compress=false;

-- Services --
USE ROLE SYSADMIN;
CREATE SERVICE  OLLAMA
  IN COMPUTE POOL OLLAMA_POOL
  FROM @YAML_STAGE
  SPEC='ollama.yaml'
  MIN_INSTANCES=1
  MAX_INSTANCES=1;

-- Usage for Weaviate Role --
USE ROLE SECURITYADMIN;
GRANT USAGE ON SERVICE WEAVIATE_PRODUCT_REVIEWS.PUBLIC.OLLAMA TO ROLE WEAVIATE_ROLE;

-- Get public Ollama URL --
USE ROLE SYSADMIN;
SHOW ENDPOINTS IN SERVICE WEAVIATE_PRODUCT_REVIEWS.PUBLIC.OLLAMA;


--------CREATE FILE FORMAT  -----
USE ROLE SYSADMIN;
USE DATABASE WEAVIATE_PRODUCT_REVIEWS
create or replace file format my_csv_format 
  type = csv 
  field_delimiter = ',' 
  skip_header = 1 
  null_if = ('NULL', 'null') 
  FIELD_OPTIONALLY_ENCLOSED_BY='"'
  empty_field_as_null = true;

-----CREATE STAGE--------
USE ROLE SYSADMIN;
USE DATABASE WEAVIATE_PRODUCT_REVIEWS;
CREATE OR REPLACE STAGE REVIEW_DATA ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

USE ROLE SECURITYADMIN;
grant all PRIVILEGES on stage REVIEW_DATA to WEAVIATE_ROLE;
grant all PRIVILEGES on schema PUBLIC to WEAVIATE_ROLE;
grant all on schema PUBLIC to role WEAVIATE_ROLE;

--------CREATE TABLES------------
USE ROLE SYSADMIN;
USE DATABASE WEAVIATE_PRODUCT_REVIEWS;
CREATE OR REPLACE TABLE 
    PRODUCT_REVIEWS (REVIEWERID varchar, ASIN varchar, 
    REVIEWERNAME varchar, HELPFUL varchar, 
    REVIEWTEXT varchar, OVERALL varchar, 
    SUMMARY varchar, UNIXREVIEWTIME varchar, REVIEWTIME varchar);

CREATE OR REPLACE TABLE 
    PRODUCTS (ASIN varchar,
    NAME varchar, 
    REVIEW_SUMMARY varchar,
    DESCRIPTION varchar, 
    FEATURES varchar);

----------PUT FILE INTO STAGE ------------
PUT file:///path/to/Musical_instruments_reviews.csv @REVIEW_DATA overwrite=true;

------------COPY DATA INTO SNOWFLAKE TABLES------------
COPY INTO PRODUCT_REVIEWS FROM @REVIEW_DATA FILE_FORMAT = (format_name = 'my_csv_format' , error_on_column_count_mismatch=false) 
  pattern = '.*Musical_instruments_reviews.csv.gz' on_error = 'skip_file';

--------Confirm data is there----------
SELECT REVIEWERID FROM PRODUCT_REVIEWS; 

-------GRANT PERMISSION TO USER --------
GRANT SELECT ON TABLE PRODUCT_REVIEWS TO ROLE WEAVIATE_ROLE;
GRANT ALL ON TABLE PRODUCTS TO ROLE WEAVIATE_ROLE;
