-- Services --
USE ROLE SYSADMIN;
DROP SERVICE WEAVIATE_DB_001.PUBLIC.WEAVIATE;
DROP SERVICE WEAVIATE_DB_001.PUBLIC.JUPYTER;
DROP SERVICE WEAVIATE_DB_001.PUBLIC.TEXT2VEC;

-- Compute Pools --
USE ROLE SYSADMIN;
DROP COMPUTE POOL WEAVIATE_COMPUTE_POOL;
DROP COMPUTE POOL JUPYTER_COMPUTE_POOL;
DROP COMPUTE POOL TEXT2VEC_COMPUTE_POOL;

-- Weaviate Database --
USE ROLE SYSADMIN;
DROP DATABASE WEAVIATE_DB_001;

-- Weaviate Warehouse --
USE ROLE SYSADMIN;
DROP WAREHOUSE WEAVIATE_WAREHOUSE;

-- Weaviate User --
USE ROLE USERADMIN;
DROP USER weaviate_user;

-- Weaviate Role --
USE ROLE SECURITYADMIN;
DROP ROLE WEAVIATE_ROLE;

-- OAuth Integration --
USE ROLE ACCOUNTADMIN;
DROP SECURITY INTEGRATION SNOWSERVICES_INGRESS_OAUTH;
